### PR TITLE
Rnd-149 Minor change to repo structure

### PR DESCRIPTION
**Pull request by fzqneo**
1. Merge two README files and move it to top level
2. Rename the source folder to src/

### CODE REVIEW

**Comment by zzsi** [comment]
@fzqneo It still makes sense to have a folder named OpenMRS (or whatever name we choose for the package), so that people can pip install our repo. In music_cortex repo, I created an OpenMRS folder with re-organized files. Do you think it makes sense to work off of that?

**Comment by fzqneo** [comment]
@bacon5885 Does it mean I should put everything in an OpenMRS folder to make sure the user can download all needed? If so it may look a bit awkward that there is a single OpenMRS/ folder under the repo.

**Comment by zzsi** [comment]
@fzqneo There will be other files in the root folder as well. 

e.g. https://github.com/scikit-learn/scikit-learn

I can move the /examples folder up to the root level.

**Comment by fzqneo** [comment]
@bacon5885 OK I reverted it back to OpenMRS/ but keep README.md and LICENSE.md at the root level. Let's make more advanced changes in next sprint.

**Comment by zzsi** [comment]
@fzqneo feel free to merge.

(next sprint) For README, I suggest we keep it simple with instructions on how to use the package, and link to another markdown file that contains the algorithm description. Some wordings on README also need to be changed. I can do a PR and let you take a look.

**Pull request merged**
